subscribers:
  robot_state: 
    topic: /state_estimator/robot_state
    queue_size: 100
    latch: false
  joy:
    topic: /joy
    queue_size: 100
    latch: false
  command_velocity: 
    topic: /locomotion_controller/command_velocity
    queue_size: 100
    latch: false