servers:
  switch_controller:
    service: switch_controller
    persistent: false
  emergency_stop:
    service: emergency_stop
    persistent: false
    
clients:
  reset_state_estimator:
    service: /state_estimator/reset
    persistent: false
