controller:
  time_step: 0.0025
  default: LocoDemo

logger:
  sampling_window: 120
  sampling_frequency: 400
  script: "/home/integration/.ros/locomotion_controller_logging.script"
  class: "std"


quadruped:
  name: starleth
  setup: minimal

notification:
  notifiers:
    default:
      topic: /notification
      queue_size: 100
      latch: false
      output_devices: 
        - "operator_screen"