controller:
  time_step: 0.0025
  default: LocoDemo

logger:
  sampling_time: 60
  script: "/home/integration/.ros/locomotion_controller_logging.script"
  class: "std"


quadruped:
  name: starleth
  setup: minimal
