controller:
  time_step: 0.0025
  default: LocoDemo

logger:
  sampling_time: 120
  publish_frequency: 400
  script: "/home/integration/.ros/locomotion_controller_logging.script"
  class: "ros"


quadruped:
  name: starleth
  setup: minimal
