subscribers:
  robot_state: 
    topic: /state_estimator/robot_state
    queue_size: 100
    latch: false
  joy:
    topic: /joy
    queue_size: 100
    latch: false
  command_velocity: 
    topic: /navigation_safety_checker/command_velocity
    queue_size: 100
    latch: false
  actuator_states: 
    topic: /sensors/actuator_states
    queue_size: 100
    latch: false
  actuator_readings: 
    topic: /sensors/actuator_readings
    queue_size: 100
    latch: false
  mocap: 
    topic: /starleth/pose
    queue_size: 100
    latch: false